In [13]:
%load_ext lab_black
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

from glob import glob

import librosa
from librosa import display


from itertools import cycle

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    plt.rcParams = {}

color_pal = plt.rcParams["axes.prop_cycle"].by_key()["color"]
color_cycle = cycle(plt.rcParams["axes.prop_cycle"].by_key()["color"])

sns.set_theme(style="white", palette=None)


import mimetypes

mimetypes.init()
import IPython.display as ipd
import IPython

# audio_files = glob("dataset/train/*.ogg")
# song, sr = librosa.load(audio_files[0], sr=None)

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black

In [12]:
! ls dataset/

genres.csv  test.csv  train  train.csv

In [15]:
pd.read_csv("dataset/train.csv").sort_values("filename")

       song_id    filename          filepath  genre_id              genre
16360        0  000000.ogg  train/000000.ogg         0         Electronic
19368        1  000001.ogg  train/000001.ogg         9      International
1093         2  000002.ogg  train/000002.ogg         6  Chiptune / Glitch
1659         4  000004.ogg  train/000004.ogg         4            Hip-Hop
11372        5  000005.ogg  train/000005.ogg        14            Country
...        ...         ...               ...       ...                ...
7413     24995  024995.ogg  train/024995.ogg         4            Hip-Hop
18831    24996  024996.ogg  train/024996.ogg         1               Rock
18898    24997  024997.ogg  train/024997.ogg         7       Instrumental
5075     24998  024998.ogg  train/024998.ogg         0         Electronic
10705    24999  024999.ogg  train/024999.ogg         9      International

[19922 rows x 5 columns]